### ISSUE TITLE
[SUGGEST] Use Harmony for method hijacking

### ISSUE THREAD

**Issue by hcoona** [spacechase0/SpaceCore_SDV#2] opened 2017-07-21 14:19 UTC
Your hijack method is very dangerous. I recommand you [Harmony project](https://github.com/pardeike/Harmony) which is also widely used for modding Rim World.

**Comment by spacechase0** [comment] 2017-07-22 14:03
I'll definitely look into it.

**Comment by spacechase0** [comment] 2017-07-29 13:04
Do you have any idea what this would be about?

```
[08:59:15 ERROR SpaceCore] Exception hijacking methods: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidProgramException: JIT Compiler encountered an internal limitation.
   at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Harmony.DynamicTools.PrepareDynamicMethod(DynamicMethod method) in G:\StardewValley\Mods\Harmony\Harmony\Tools\DynamicTools.cs:line 115
   at Harmony.MethodPatcher.CreatePatchedMethod(MethodBase original, List`1 prefixes, List`1 postfixes, List`1 transpilers) in G:\StardewValley\Mods\Harmony\Harmony\MethodPatcher.cs:line 73
   at Harmony.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo) in G:\StardewValley\Mods\Harmony\Harmony\PatchFunctions.cs:line 59
   at Harmony.PatchProcessor.Patch() in G:\StardewValley\Mods\Harmony\Harmony\PatchProcessor.cs:line 63
   at Harmony.HarmonyInstance.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler) in G:\StardewValley\Mods\Harmony\Harmony\HarmonyInstance.cs:line 76
   at SpaceCore.Overrides.NewGame1.hijack(HarmonyInstance harmony) in G:\StardewValley\Mods\SpaceCore\Overrides\NewGame1.cs:line 30
   at SpaceCore.SpaceCore.Entry(IModHelper helper) in G:\StardewValley\Mods\SpaceCore\SpaceCore.cs:line 41```

**Comment by hcoona** [comment] 2017-07-31 08:50
I'm not sure. I didn't meet this exception before.

Are you trying it on Windows? There is a patch from me but pending on PR for Windows memory access violation issue. Maybe you can try this one. https://github.com/pardeike/Harmony/pull/28

**Comment by spacechase0** [comment] 2017-07-31 16:04
Hmm, no, that doesn't appear to fix it.

I've narrowed it down to the `Game1.setGraphicsForSeason` prefix patch. Even having the prefix empty causes the error.

**Comment by hcoona** [comment] 2017-08-01 06:11
Would you like to share your codes in seperated branch so I could help to take a look at it?

**Comment by spacechase0** [comment] 2017-08-01 12:41
It should be in master.

**Comment by hcoona** [comment] 2017-08-01 13:01
I built & deployed the latest version (fb28992). Do you have any idea about how to reproduce your issue?

My environment:
* Windows 10
* VS2017
* StardewValley latest on Steam

**Comment by spacechase0** [comment] 2017-08-01 13:16
The exception appears when the game loads, in the SMAPI console, right after the "Loaded X mods".

**Comment by hcoona** [comment] 2017-08-01 13:21
Still cannot reproduce it, neither for existing saves or new game. I removed the mod folder "SpaceCore" & rebuilt to automatically deploy it.

![screenshot](https://user-images.githubusercontent.com/712433/28827195-5889d930-76ff-11e7-97f4-d7e15e3551b1.png)

**Comment by spacechase0** [comment] 2017-08-01 13:42
Hmm. I'm getting it even on another computer (although I copied my workspace).

I'll set up a fresh workspace later today and see if that is the issue.

**Comment by spacechase0** [comment] 2017-08-01 18:45
Huh. That fixed it. No idea what the issue was though.

Thanks for telling about this library!

**Comment by hcoona** [comment] 2017-08-02 12:39
Would you like to share the codes in seperated branch so maybe I could help you with it.


2017年8月1日 +0800 AM12:04 Chase W ，写道：

**Comment by spacechase0** [comment] 2017-08-05 19:08
Someone just reported an issue on Mac:

```
[14:26:45 ERROR SMAPI] SpaceCore failed on entry and might not work correctly. Technical details:
Failed loading type '': System.TypeLoadException: Could not load type StardewValley.Game1, Stardew Valley, Version=1.2.6400.27469, Culture=neutral, PublicKeyToken=null while decoding custom attribute
at (wrapper managed-to-native) System.MonoCustomAttrs:GetCustomAttributesInternal (System.Reflection.ICustomAttributeProvider,System.Type,bool)
at System.MonoCustomAttrs.GetCustomAttributesBase (ICustomAttributeProvider obj, System.Type attributeType, Boolean inheritedOnly) <0x1092dbd80 + 0x00071> in <filename unknown>:0
at System.MonoCustomAttrs.GetCustomAttributes (ICustomAttributeProvider obj, System.Type attributeType, Boolean inherit) <0x1092daf90 + 0x000bc> in <filename unknown>:0
at System.RuntimeType.GetCustomAttributes (Boolean inherit) <0x1165bc1f0 + 0x0002f> in <filename unknown>:0
at Harmony.HarmonyMethodExtensions.GetHarmonyMethods (System.Type type) <0x1636f5510 + 0x0001d> in <filename unknown>:0
at Harmony.HarmonyInstance.<PatchAll>b__6_0 (System.Type type) <0x1636f5350 + 0x00026> in <filename unknown>:0
at Harmony.CollectionExtensions.Do[T] (IEnumerable`1 sequence, System.Action`1 action) <0x1636f48a0 + 0x00090> in <filename unknown>:0
at Harmony.HarmonyInstance.PatchAll (System.Reflection.Assembly assembly) <0x1636f4780 + 0x000d4> in <filename unknown>:0
at SpaceCore.SpaceCore.Entry (IModHelper helper) <0x1636f4150 + 0x00241> in <filename unknown>:0
at StardewModdingAPI.Program.LoadMods (StardewModdingAPI.Framework.IModMetadata[] mods, StardewModdingAPI.Framework.Serialisation.JsonHelper jsonHelper, StardewModdingAPI.Framework.SContentManager contentManager, IList`1 deprecationWarnings) <0x15363a6e0 + 0x02b33> in <filename unknown>:0 
```

**Comment by hcoona** [comment] 2017-08-06 05:29
I think this is a compiling issue. The referenced type `StardewValley.Game1, Stardew Valley, Version=1.2.6400.27469` is against Windows version of StardewValley, which is not exactly match the Mac version.

I tested my mods, they reported almost the same error but still works fine. I'll try compile with Mac StardewValley to see whether it could be solved.

**Comment by hcoona** [comment] 2017-08-06 06:16
Compile with Mac version sovled the issue on Mac but not compatible with Windows version game.

The reason is because the Attribute compiled with version info, for example:

```csharp
[HarmonyPatch(typeof(global::StardewValley.Farmer), "getMovementSpeed")]
internal class PatchFarmerGetMovementSpeed
    {
        internal static void Postfix(ref float __result)
        {
            __result += Main.Config.FasterSpeed;
        }
    }
```

When compiling, the version of type `global::StardewValley.Farmer` is compiled into the assembly which is fixed to Windows version of the game. So it is not compatible with the other versions game.

To sovle it, there are 2 solutions:

1. Build the mod for each version. (Verified but too expensive)
2. Use Harmony manual patching feature to eliminate the attribute info. See document [here](https://github.com/pardeike/Harmony/wiki/Bootstrapping#manual-patching). It works to me.

**Comment by spacechase0** [comment] 2017-08-06 11:37
Hmm. SMAPI is supposed to rewrite those differences, so I never would have suspected that.

**Comment by spacechase0** [comment] 2017-08-11 14:59
Going to go ahead and close this since it appears to (kinda) be a SMAPI bug.

Although, could you look and see if you can reproduce the same original exception in [Custom Farm Types](https://github.com/spacechase0/CustomFarmTypes)?

**Closed as completed by spacechase0** 2017-08-11 14:59 UTC

**Comment by Digus** [comment] 2017-12-07 01:19
@hcoona I'm having this issue as well and would like to apply your second solution. But I don't know excellently what you mean by "eliminate the attribute info", could you show an example? I already look into the documentation and applied the Manual Patching. But I can't even test to learn how to remove the version info since I don't have a Mac.

**Comment by hcoona** [comment] 2018-01-04 02:05
@Digus sorry for the late response because I'm really busy in past month.

The 2nd solution just means "Use manually `typeof(xxx)` instead of attribute tag", because C# compiler would write the type info when compiling attribute tag while `typeof(xxx)` come out during runtime. The type mismatch between your compiling referenced dll & Mac version dll, but always consistant during runtime.

Hope my explaination help to you.


For example, do not use attribute:
```csharp
[HarmonyPatch(typeof(global::StardewValley.Farmer), "getMovementSpeed")]
internal class PatchFarmerGetMovementSpeed
{
    internal static void Postfix(ref float __result)
    {
        __result += Main.Config.FasterSpeed;
    }
}
```

Use manual register:
```csharp
var harmony = HarmonyInstance.Create("com.company.project.product");
var original = typeof(global::StardewValley.Farmer).GetMethod("getMovementSpeed");
var postfix = typeof(PatchFarmerGetMovementSpeed).GetMethod("Postfix");
harmony.Patch(original, null, new HarmonyMethod(postfix));
```

**Comment by Digus** [comment] 2018-01-04 02:46
@hcoona 
Thank you for the answer.
After thinking about what you said back then, I came to the solution you are showing now.
The person that reported the problem never answered me back if the code worked.
So it's good to know what I did was right.
If you are curious, here is my code: 
https://github.com/Digus/StardewValleyMods/blob/master/ButcherMod/AnimalHusbandryModEntery.cs

**Comment by hcoona** [comment] 2018-01-05 12:54
Cool! Glad to know about it.
